version: "3"
services:
  tensorflow-serving:
    image: tensorflow/serving:latest
    restart: always
    ports:
      - 8500:8500
      - 8501:8501
    volumes: 
      - ${MODEL_PATH}:/models/${MODEL_NAME}
      - ${MODELS_CONFIG_PATH}:/models/models.config
    command: --model_config_file=/models/models.config --allow_version_labels_for_unavailable_models=true


